sde: /opt/p4-sde/bf-sde-9.13.2
sde_install: "{{ sde }}/install"

os_environment:
  - key: SDE
    value : "{{ sde }}"
  - key: SDE_INSTALL
    value : "{{ sde_install }}"

sde_path: "{{ sde_install }}/bin"

ansible_python_interpreter: /usr/bin/python3

p4_restart_group: p4-restart # group name for p4-restart users
restart_install_dir: "/home/{{ ansible_user }}/.restart-super"
ssh_auth_config: "{{ restart_install_dir }}/ssh_authorized_user"

restart_users:
  - p4-restart
  - zhihaow
  - pgiaccone
  - msacco
  - aangi
  - ojasson

users:
  - ubuntu # TODO remove
  - "{{ restart_users }}"
