- name: Ensure requirements in place
  package:
    name:
      - libguestfs-tools
      - python3-libvirt
      - python3-lxml
      - libnss-libvirt
      - libvirt-daemon-system
      - qemu-system
    state: present

- name: Start service libvirt
  service:
    name: libvirtd
    state: started

- name: Add admin user to libvirt group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: libvirt
    append: yes
    state: present

- name: Configure libvirt VM name resolution
  lineinfile:
    path: /etc/nsswitch.conf
    regexp: '^hosts:'
    line: 'hosts:          files mdns4_minimal libvirt libvirt_guest dns myhostname mymachines [NOTFOUND=return]'


