# create VM for user
- name: Provision KVM VMs - bridged on dataplane network
  hosts: servers
  become: true

  vars:
    reconfigure_running_vms: false  # force re-define existing libvirt VMs (with shutdown)

  roles:
    - ../roles/kvm-pre
    # - ../roles/kvm-debian-bridged-net-pre
    # TODO test this
    - ../roles/kvm-sriov
    - ../roles/kvm_provision


# Bootstrap user on P4 switches
# TODO this should actually just create the user...netplan should be already there
- name: Configure environment for P4 switch
  become: true
  hosts: p4switches  
  roles:
    - ../roles/bootstrap
    # - ../roles/netplan no need of this whenever we add a new user
    # - ../roles/tofino-config also no need of this, does not depend on specific users
    

# Bootstrap VM environemnt
- name: Bootstrap VMs environment
  become: true
  hosts: 
    - vms
  roles:
    - ../roles/bootstrap
    - ../roles/netplan    

# create user on server and add to webapp db
- name: Configure user on servers
  become: true
  hosts: restsrv01
  tags:
    - run
  tasks:

    - name: Create server users
      ansible.builtin.user:
        name: "{{ item }}"
        shell: /bin/bash
        password: "{{ 'p4-restart' | password_hash('sha512', 'mysecretsalt') }}"
        update_password: on_create
        state: present
      with_items: "{{ users }}"
 
    - name: Check user db exists
      stat:
        path: "{{ tofino_rsvp_install_dir }}/webapp/.data/users.csv"
      register: user_db
    
    # NOTE: restart_users only here. These are the users that will be added to the webapp db
    - name: "Adding Tofino users to webapp db: {{ tofino_rsvp_install_dir }}/webapp"
      ansible.builtin.lineinfile:
        path: "{{ tofino_rsvp_install_dir }}/webapp/.data/users.csv"
        line: "{{ item }}"
      with_items: "{{ restart_users }}"
      when: user_db.stat.exists