- name: Provision KVM VMs - bridged on dataplane network
  hosts: servers
  become: true

  vars:
    reconfigure_running_vms: false  # force re-define existing libvirt VMs (with shutdown)

  roles:
    - ../roles/kvm-debian-bridged-net-pre
    - ../roles/kvm_provision