
- name: Deploy P4 booking dashboard Web app
  # to keep the ssh-agent socket when executing with root, used to install keys 
  # on tofino switches from the restsrv01 machine using the permissions of the 
  # ssh-agent on the ansible client machine
  # https://stackoverflow.com/questions/24124140/ssh-agent-forwarding-with-ansible
  become_flags: "--preserve-env=SSH_AUTH_SOCK"
  hosts: restsrv01
  roles:
    - ../roles/p4-book-webapp