# 
# Run with --tags option to run specific tasks
#
#       ansible-playbook -i inventory.yaml ./playbooks/debian-kvm-p4dev-vm.yaml --tags sriov 
#

- name: Provision VMs, add only bridge interface
  hosts: servers
  become: true
  vars:
    reconfigure_running_vms: false
  roles:
    - ../roles/kvm-pre
    - ../roles/kvm-debian-bridged-net-pre
    - ../roles/kvm_provision
    